spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Giantsgram?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.naver.com
    port: 465
    username: zzangth95@naver.com
    password: ">th7942315"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.comserver:
  port: 80
